

log_dir: '../log/AWA2.log'
dataset_root: '../dataset'
dataset_name: 'AWA2'
writer_path: '../runs/AWA2'
device: 'cuda:1'
k_cluster: 3
backbone: 'vit-base'
epoch: 100

lambda_cls_loss: 1.0
lambda_project_loss: 1.0
lambda_edge_loss: 0.1
lambda_contrastive_loss: 0.7
lambda_margin_loss: 0.4
margin_dist: 0.3
grad_clip_value: 1.0

train_batch_size: 128
test_batch_size: 1024
init_temp: 0.01
semantic_temperature: 1.0
visual_temperature: 1.0
manual_seed: 888

optimizer: 'Adam'
momentum: 0.00
alpha: 0.9
weight_decay: 0.000001
lr: 0.002
lr_decay: 0.9
swa_lr: 0.00001
swa_annealing_epoch: 20
swa_annealing_strategy: 'cos'
gamma: 2.1
scale: 30.0

visual_feat_num: 2048
semantic_feat_num: 85
trans_feat_num: 2048
